sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/bind
    - secure: "noWpxbcy2JYPT5VsIlu0qhYnUIM1Ls4vmQGRtdQKzp+X2uIOBolaz1gPAg0RhwTQJn56YQDBrKTPxPxZqK0leWYjO6YTin8nReZO8SGVc8OkRn/oHSHNOC/mjl+8XDDML0+3ymwFPr2PHjhhK779TzKwBY97oHhUTjBcvtw3LarYSywvB6dB1DXsPIFWHuTFh86myPiDIkKlcg+M4cMKZzcuuYTEVL81SD2tDHfsYHzak4YGt6aomduUlGvbnwvnsLqwLPhnW+IBtQ75vRKulU4hie0aWIt0nduzEMndrQySlLF3H6xlAO8ms9V6Aw0c+nEX6KkX8MVM7N+8fe/HiC6RZwcg86dauByfAGJTnpFgGP3K9/XBsOdQKj1cpIhfQSKfyQxzkvCyKkybOff/uoOUCxRRa/1rG2fUBkHosND1VOCLOCrmsucB0cPzsBRUd+WpeFhybrSkBMkBWherHSB/Xxp2Yxn+5p60ttSNsxFThfyJayS4XVrS9hd7Ot9XenoaRAVeCnK/z1coP6GlIadKYMep05wx5ROeALpplAKw6OEOL8U+lOASyU3A1AFEF9PKCOg9GwV2yPVV7HfHQ3LwoWsVNhg4ZTsBHlw5E0vMASC1x3Gl6EtNganoLPwfKjtSQoGmlnicfpxgRQJBvGrWV6nlNZ77pSjbexgNMM0="
