sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/bind
    - secure: "GDuKowzxw3vJsRG7MuQxNjp0ffUVr0tfcX1kh12+HikbX6z+OHfx8rwkoYtR9slGjAx/EXhVGocyw+kCXO9HtcM8SBs06mBTGmkeiyO7SfBQy9Pa2OA7sv6DT6YY6+JJro8eK18EqpUTqGpHfcbuuTg2+0TEgF7H+JpUuje1q/VOGqe56E1snW9KXsWSALeW76wxuffPxrYeFT76e+aB3gKAcYZJeKKneGr5BqaNEZEUkSsNfT6MhpRvTEW4Y8OkuLSmpgEVEA/2/BnNIGU7awJlBnaJD4Vl1bQ26EPnr/EQmrAIWueZcqoqR3BU2HF9frs8cFhuCqS25TXU4GrQe92eTKRyUhgUmiU07x5/WEQ/f0Pg1ESVyEbD0zWpyjYf+zZVSFaj1Zl/gj+jAL1oJcCkzeK7TXwxUtusM7c92vle9/aTXNw7o6SImpXWFdzIk+isGOsatVC2zRinVxBk3+9qSlQ50M1gU9+UFCZeCg9LTVNqES4MS9eqMxJbcIk1FKNyQga6y/Zu+/E+Y4mPTHPye/xCzROpbJ8yu+odK0kELHMMP3EGuW5oYmKD52bEoEVvMdkCNVaO1cexllF8eEGVxb2GHIreCpRZh0OWaXNZAoguijq+aVKX2NJmCEs8lPNEo1F98n4PJwolq6zJzaFHPo5dZiEXVcG5LBaQ6Pg="
