sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/bind
    - secure: "v3/BvnKQqaqTDrJ9f5PEPn3BtYZe1viZHZJMPiavP+wXxGPInZ54SRcpEEcYZNLBpsUCC/A+8OX21CseGreYnLZyPuqaP3HldLgyAbNvoLVYteXOsSItiN3RFMKo9JQ4ztYfpMbyjYGYs/L9cNncS5beed3Wf54HtP/5hc7g31fLxGLYE+91NkDq0Dk+EDmC2HuzER38d5Z8/+VhI/1Q7uqimhrlT0nX7JiUHj0Y3s55uSafkH0O3n2Vz+A3w2OC+Fw688i3HNWQ/Shrw6iTFhaBpv3/KLmHLPRo2lNJddHZb6yMN+zmEYGRTMm/Ug6pW3beKz2kXjJOndtH9IsD6KCWCPpuuZuIl+owl98X+/fSK7pojKKQ1lxiE3n1Uer2sSGZ384ElhtmeaBog3ImLKdZ8iZzrVIh1wlSmbf+8b6ZGfCaqEbgBXp8Z4cAj0d8hKF060XTPUPdtEE8MqHoM0yVOlQme3YQlNrIvnllZlOcTX7/Tdj58nOv0tfJ8U/vjay2ftl9rsBx11ZMtBQzVLnky0V/9p2BKnlEnIyTmA12c++vvRDm2uODK9D7jrwLlaaN/qswyKX8mWFnf/j0zEGo/iM9zHNgOqRY/GPSU2ViiX7wtEEH/c5diAoJfJ+pM13FrfGFrfe+0yRrx3CjIEhv6lH0gc7JKnutwx02Rdo="
