sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/bind
    - secure: "QR4WXUNQUDS4bdmlZZwbSW/X4ca4kF96zZGIBbJp31wHa+U0sDEpVixjaIWkYy5QG6VZiqjdrEKfQYCz05OO+Dv7RgPtZD17d35Py6+16MRsDS9S9OmZYADwHGfDAPY+zgy/nEs1CQdUnUkRbMDSlqPkk1WO0TBBPWnK2bsMs1SwE2m/Z0oF//Pid41HaAPk2Gws+NbhlV1XwYF5/Q0GdYIgLz5ZQx2pXFhqfBBX2uNzZ9DFyFbkonXxn28tbeMs5s30kqDJl67hJTPnNfaW8bgSvmDU+UpuhOs0ruarFbXwchE0xIA6m0+mSjG3R+xn2sxX0ffEipYjCLauYfkSZ85yUrGF9+50m+q5l8NMkAJOsATwBShZLfe4FnFBdy/jBShl1ilr8HhTA6MO69Zlna4VtxhZgJi2fjDnzZZj1bPJVVBJmMCJW+vescLrQIFAY8bS4+suF9W1+PX5nsNhK6vGJx85i7glQJSWg+zTN/ONQ1tni1sQrQTmrpH4+I5xS8ybYMoeGg4jD3DoqfEn61K3rILCWYFTwopoeYyHLmiMnlsIyMbeZIbo4fH/FC+H1+KEDL5Jo+IV1QXGjvIKuD+BOozjwM7ERngR4WpcHda658pUEMg2VN7BIoq5ZVjVF7sHCGdXsl43QELdo7+4m5+o+Sq+ZwypMjuf1KkhVoE="
